piyoki/nixos-config

- home/apps/fish/config.fish
- home/packages/windowmanager/hyprland/browser/default.nix
- home/services/gnupg/default.nix
- feat(home/service/gnupg): add sops,age
- patch(app/fish): add default gnupg key
- feat(home/pkg): add qutebrowser
> qutebrowser

- home/apps/fish/config.fish
- home/services/gnupg/default.nix
- feat(home/service/gnupg): add sops,age
- patch(app/fish): add default gnupg key
> feat: integrate encryption

- flake.nix
- home/packages/windowmanager/hyprland/system/default.nix
- system/default.nix
- system/security/default.nix
- system/services/default.nix
- system/services/displaymanager.nix
- system/users/default.nix
- feat(system): set gdm as default display-manager
- feat(system: add security module
- patch: tidy up displaymanager module
- patch: swap to sddm as default display-manager
> feat(system): set sddm as default display-manager

- flake.nix
- system/services/cron.nix
- system/services/displaymanager.nix
- system/users/default.nix
- feat(cron): add restart-scdaemon systemd-timer
- refactor: inherit user from flake var
- patch: user absolute path for gpgconf
> feat(cron): add restart-scdaemon systemd-timer

- flake.lock
- system/services/gnupg.nix
- templates/app/from_file.nix
- templates/app/from_github.nix
- feat(template/app/from_file): add home file example
- feat(template/app/from_github): add home file example
- patch: update tmux upstream
- feat(gnupg): add shellInitCmd for gpg-agent
> feat(gnupg): add shellInitCmd for gpg-agent

- flake.lock
- home/maintenance/ansible/default.nix
- home/maintenance/default.nix
- feat: introduce ansible module
- chore: sync upstream ref
> feat(home/maintenance): add ansible module

- flake.lock
- flake.nix
- home/secrets/default.nix
- system/default.nix
- system/networking/default.nix
- system/networking/sdwan.nix
- system/secrets/default.nix
- system/secrets/sdwan.nix
- feat(creds): persist sdwan secrets
- feat(system/networking): add sdwan module
- chore(flake): sync secrets,home-estate
> feat(system/secrets): add sdwan module

- system/services/dconf.nix
- system/services/default.nix
- system/services/displaymanager.nix
- system/services/windowmanager.nix
- system/services/xdg-portal.nix
- patch: disable sddm
- refactor(system/service): separate dconf configs
- patch(system/service): use xdg-portal-desktop-hyprland
- refactor(system/service): separate windowmanager module
> refactor(system/service): rework xdg-portal, disable sddm

- home/packages/devops/default.nix
- system/services/powermanagement.nix
- system/services/virtualization.nix
(cherry picked from commit 1078b93a7eca982d60bd363cff140c4650d37e46)
> patch(system): completely disable virtualization

- home/secrets/default.nix
- home/services/systemd/README.md
- profiles/thinkpad-x1-carbon/hardware-configuration.nix
- system/secrets/default.nix
- system/secrets/samba.nix
- system/services/cifs-mount.nix
- system/services/powermanagement.nix
- docs(home/systemd): update systemd readme
- refactor(system): rework cifs-mount module
- refactor(system): disable tlp and add bat_threshold systemd unit
- feat(system): enable i915.psr (Panel Self Refresh)
> patch(system): apply powermanagement tweaks

- flake.lock
- home/apps/swaync/default.nix
- home/packages/windowmanager/hyprland/system/default.nix
- feat(home/app): add swaync
- chore(flake): sync upstream
> feat(home/app): add swaync

- flake.lock
- home/packages/wayland/default.nix
- system/secrets/samba.nix
- system/services/default.nix
- system/services/windowmanager.nix
- **patch(system): disable cifs-automount**
- **chore(flake): update input.home-estate**
- **patch: do not force to enable xwayland**
> fix(system): apply system patches to fix hang issue

- .github/workflows/cron-sync-hyprland-upstream.yml
- flake.lock
- **ci: add cron-sync-hyprland-upstream workflow**
> ci: add cron-sync-hyprland-upstream workflow

- home/services/systemd/powermanagement/swayidle.nix
- system/services/powermanagement.nix
- **patch(system/power): unmount-samba before-sleep**
> patch(system/power): unmount-samba before-sleep

- home/services/xdg/default.nix
- system/security/default.nix
- system/services/dconf.nix
- system/services/default.nix
- system/services/gnome-keyring.nix
- system/services/xdg-portal.nix
- **feat(system): enable gnome-keyring**
- **refactor(system): demise dconf; migrate to xdg-portal**
- **fix: resolve conflicts**
> patch(system): apply general patches

- home/packages/development/default.nix
- home/packages/development/languages/default.nix
- home/packages/development/languages/java/default.nix
- home/packages/development/languages/python/default.nix
- system/default.nix
- system/environment/default.nix
- **feat(home/pkgs): add maven**
- **feat: add extra dev tools**
- **feat(home): set default browser**
- **feat(system/pkgs): add deadnix**
> feat: add extra dev packages

- flake.lock
- system/services/powermanagement.nix
- themes/fonts/common-fonts.nix
- **feat(system/powermanagement): add battery threshold confs (#63)**
- **chore(flake): update flake.lock to sync input.dotfiles**
> feat(system/fonts): add maple-mono font

- flake.lock
- system/services/default.nix
- themes/fonts/custom-fonts.nix
- **feat(system/font): add dogica font**
- **patch(system): disable greetd temporarily**
> feat(system/font): add dogica font

- flake.nix
- profiles/thinkpad-x1-carbon/configuration.nix
- profiles/thinkpad-x1-carbon/hardware-configuration.nix
- system/default.nix
- system/internationalisation/default.nix
- system/internationalisation/i18n.nix
- system/internationalisation/time.nix
- **feat/refactor(system): separate internationalization module**
- **refactor(system): rework basic system module**
- **optimize(flake): better modularity design**
> refactor(flake): multi-system prep

- justfile
- system/packages/core.nix
- **feat(system/pkgs): add just**
- **ci: integrate justfile to speed up tasks**
> ci: integrate justfile to speed up tasks

- flake.lock
- flake.nix
- home/apps/hypr/default.nix
- home/apps/waybar/default.nix
- justfile
- profiles/nuc-12/home.nix
- profiles/nuc-12/modules/dotfiles.nix
- system/default.nix
- **ci(justfile): add garbage-cleanup recipe**
- **refactor(home): modularize app configs (hypr**
> refactor(home): modularize app configs (hypr,waybar)

- home/common/options.nix
- home/default.nix
- home/vars.nix
- **chore(home/common/option): add reference**
- **feat(home): add vars**
> patch(home): apply tiny patches

- flake.lock
- flake.nix
- system/services/openssh/default.nix
- **chore(flake): switch to unstable-small**
- **patch(system/openssh): PermitRootLogin: prohibit-password**
> patch(flake): use nixpkgs-unstable-small

- flake.nix
- shared/modules/system/tmpfs/persistent/base.nix
- shared/nixos.nix
- system/networking/sdwan.nix
- **optimize(flake): better inputs modularization control**
- **chore(shared/nixos.nix): add reference to workaround**
> optimize(flake): better inputs modularization control

- profiles/mars/configuration.nix
- profiles/mars/hardware-configuration.nix
- profiles/nuc-12/hardware-configuration.nix
- profiles/thinkpad-x1-carbon/hardware-configuration.nix
- **patch(profiles/mars): switch to grub boot**
- **patch(profiles/nuc-12**
- **patch(profile): revert back to systemd-boot**
> patch(profiles): apply boot tweaks

- flake.lock
- flake.nix
- home/assets/wallpaper.nix
- **feat(flake): add inputs.assets**
- **patch(home/assets): fetch wallpapers from assets input**
> patch(home/assets): fetch wallpapers from assets input

- flake.lock
- flake.nix
- justfile
- **patch(flake): add huamea input**
- **ci(justfile): add show recipe**
- **refactor/optimize: leverage mergeAttrsList for better profile import**
> refactor/optimize: leverage mergeAttrsList for better profile import

- .pre-commit-config.yaml
- flake.nix
- home/services/encryption/server.nix
- justfile
- profiles/server/felix/hardware-configuration.nix
- shared/modules/secrets/default.nix
- **chore(pre-commit): add local shell hooks**
- **ci(justfile): add lint recipe**
- **style: apply fix suggested by statix,deadnix**
> chore/style(pre-commit): add local shell hooks

- .gitignore
- flake.nix
- justfile
- **chore(gitignore): ignore .env**
- **ci(justfile): enable load-dotenv; set default profile from env**
- **ci(justfile): add check recipe**
- **patch(flake): remove devShell**
> ci(justfile): enable load-dotenv; set default profile from env

- flake.nix
- profiles/workstation/nuc-12/configuration.nix
- shared/lib/default.nix
- shared/modules/system/tmpfs/persistent/default.nix
- **feat(shared): add sharedLib attr**
- **feat(flake): add genSpecialArgs function**
- **fix(shared/modules/persistent: remove trailing space**
> feat(shared): add sharedLib attr

- profiles/server/felix/configuration.nix
- profiles/server/felix/home.nix
- profiles/server/mars/configuration.nix
- profiles/server/mars/home.nix
- profiles/workstation/nuc-12/configuration.nix
- profiles/workstation/nuc-12/home.nix
- profiles/workstation/thinkpad-x1-carbon/configuration.nix
- profiles/workstation/thinkpad-x1-carbon/home.nix
- **refactor(profile/nuc-12): adopt relativeToRoot path**
- **refactor(profile/thinkpad-x1-carbon): adopt relativeToRoot path**
- **refactor(profile/mars): adopt relativeToRoot path**
- **refactor(profile/felix): adopt relativeToRoot path**
> refactor(profiles): adopt relativeToRoot path

- home/apps.nix
- home/apps/default.nix
- home/default.nix
- shared/lib/default.nix
- system/default.nix
- **feat(shared/lib): add scanPath func**
- **refactor(home): adopt scanPath imports**
- **refactor(system): adopt scanPath imports**
> refactor:(home,system): adopt scanPath imports

- profiles/server/sdwan-gateway/modules/services.nix
- profiles/server/tailscale-gateway/modules/services.nix
- system/networking/udp-gro-forwarding.nix
- system/packages/server.nix
- system/services/powermanagement/laptop.nix
- **feat(system/networking): add udp-gro-forwarding module**
- **feat(profile/server/{tailscale,sdwan}): enable udp-gro-forwarding**
> feat(system/networking): add udp-gro-forwarding module

- .gitignore
- flake.lock
- flake.nix
- justfile
- profiles.nix
- shared/modules/microvm/firecracker.nix
- **chore(ignore): ignore var.img**
- **feat(flake): add inputs.microvm**
- **ci(justfile): add run recipe**
- **chore(profiles): add firecracker**
- **feat(shared/modules/microvm): add firecracker profile**
- **ci(justfile): add build recipe**
- **feat(flake): add genPkgs func**
> feat(flake): add microvm support

- profiles/server/felix/configuration.nix
- profiles/server/felix/modules/networking.nix
- profiles/server/mars/configuration.nix
- profiles/server/mars/modules/networking.nix
- shared/modules/containerisation/docker-compose.nix
- **feat(shared/modules): add dedicated docker-compose-systemd module**
- **refactor(profiles/server/{felix,mars}): separate networking config to module**
> feat(shared/modules): add dedicated docker-compose-systemd module

- flake.lock
- home/apps/atuin/config.toml
- home/apps/atuin/default.nix
- home/packages/windowmanager/hyprland/terminal/default.nix
- home/services/atuin-client/config.toml
- home/services/atuin-client/default.nix
- home/services/default.nix
- **chore(flake): update flake lock**
- **feat(home/service): add atuin-client module**
- **refactor(home/service): integrate scanPath for submodules**
- **refactor(home/app/atuin): demise atuin app configs**
> feat(home/service): add atuin-client module

- flake.nix
- profiles.nix
- shared/modules/secrets/default.nix
- shared/server/age-key.nix
- shared/server/secrets/age-key.nix
- shared/server/secrets/atuin-server.nix
- **feat(profiles): add genProfile func**
- **refactor(shared/server/secrets): rework secrets modules**
- **feat(shared/modules/secrets): add atuin secrets**
> feat(shared/modules/secrets): add atuin secrets

- profiles/workstation/nuc-12/hardware-configuration.nix
- profiles/workstation/nuc-12/home.nix
- profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
- profiles/workstation/thinkpad-x1-carbon/home.nix
- shared/nixos.nix
- shared/server/secrets/age-key.nix
- shared/server/secrets/atuin-server.nix
- system/packages/misc.nix
- **feat(system/pkgs): add libva-utils**
- **chore(shared/server/secrets): add reference**
- **chore(profiles/workstation): add references**
- **chore(profile/workstation/home): remove unnecessary config attr**
- **feat(shared/nixos): add extra binary cache servers**
> patch(system): apply some general tweaks

- justfile
- **ci(justfile): rename recipe update-input -> upp**
- **ci(justfile): refine syntax, add annotations**
> ci(justfile): refine syntax, add annotations

- flake.lock
- home/apps/alacritty/default.nix
- shared/modules/system/tmpfs/persistent/default.nix
- shared/modules/system/tmpfs/persistent/files/common-home-files.nix
- **patch(shared/persistent): ignore .tmux.conf**
- **feat(home/app): persist alacritty configs**
- **chore(flake): update flake.lock**
> feat(home/app): persist alacritty configs

- flake.lock
- flake.nix
- home/apps/alacritty/default.nix
- home/apps/dunst/default.nix
- home/apps/fish/default.nix
- home/apps/hypr/default.nix
- home/apps/kitty/default.nix
- home/apps/lazygit/default.nix
- home/apps/lf/default.nix
- home/apps/nvim/default.nix
- home/apps/qutebrowser/default.nix
- home/apps/rofi/default.nix
- home/apps/swappy/default.nix
- home/apps/swaylock/default.nix
- home/apps/tmux/default.nix
- home/apps/waybar/default.nix
- **chore(flake): use universal dotfiles upstream**
- **refactor(home/app): rework app modules**
- **chore(flake): update flake.lock to sync input.dotfiles**
- **chore(flake): update flake.lock**
> refactor(home/app): rework app modules

- profiles/server/felix/hardware-configuration.nix
- profiles/server/mars/hardware-configuration.nix
- profiles/server/sdwan-gateway/hardware-configuration.nix
- profiles/server/tailscale-gateway/hardware-configuration.nix
- profiles/workstation/nuc-12/hardware-configuration.nix
- profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
Reverts yqlbu/nixos-config#162
> Revert "optimize(profiles): use lto-kernel for better performance"

- flake.lock
- home/apps/foot/default.nix
- home/apps/kitty/default.nix
- home/packages/windowmanager/hyprland/productivity/default.nix
- **feat(home/pkgs): add foot**
- **refactor(home/app): demise kitty**
- **feat(home/app): persist foot config**
> feat(home/pkgs): add foot

- flake.lock
- flake.nix
- **chore(flake): update inputs.{chaotic,chaotic-kernel}**
- **chore(flake): update inputs.{home-manager,microvm,nixpkgs-wayland}**
- **patch(flake): update nixpkgs dependency**
> chore(flake): update inputs

- .gitignore
- README.md
- flake.nix
- justfile
- **docs(readme): update upstream inputs list**
- **chore(gitignore): ignore result***
- **ci(justfile): add nix-fast-build recipes**
- **feat(flake): add inputs.nix-fast-build**
> feat(flake): integrate nix-fast-build

- docs/overlays-usage.md
- home/packages/windowmanager/hyprland/im/default.nix
- shared/overlays/default.nix
- shared/overlays/webcord.nix
- **feat(shared/overlays): add webcord overlays**
- **feat(home/app): add webcord; demise vesktop**
- **patch: update overlays definition**
- **docs: add overlays-usage**
> feat(shared/overlays): add webcord overlays

- flake.lock
- home/services/git/default.nix
- home/services/git/gitconfig
- profiles/workstation/nuc-12/home-secrets/gitconfig.nix
- profiles/workstation/thinkpad-x1-carbon/home-secrets/gitconfig.nix
- **patch(profiles/workstation): demise gitconfig secret config**
- **feat(home/services): add git module**
- **feat(home/service/git): add msg alias**
- **chore(flake): update inputs.secrets**
> feat(home/services): add git module

- README.md
- flake.lock
- flake.nix
- **chore(flake): add inputs.pilots**
- **docs(readme): add pilots to upstream list**
> chore(flake): add inputs.pilots

- flake.lock
- home/apps/qutebrowser/default.nix
- **feat(home/app/qutebrowser): add scripts/**
- **feat(home/app/qutebrowser): add python3-adblock**
> patch(home/app/qutebrowser): apply extra qutebrowser tweaks

- flake.lock
- home/apps/qutebrowser/default.nix
- home/packages/windowmanager/hyprland/browser/default.nix
- shared/overlays/default.nix
- shared/overlays/qutebrowser.nix
- **feat(home/pkgs): adopt qutebrowser_nightly**
- **refactor(shared/overlays): remove qutebrowser module**
> feat(home/pkgs): adopt qutebrowser_nightly

- flake.lock
- home/apps/fzf/default.nix
- home/apps/fzf/fzfrc
- **feat(home/apps): persist fzf configs**
> feat(home/apps): persist fzf configs

- home/packages/windowmanager/hyprland/browser/chromium.nix
- home/packages/windowmanager/hyprland/browser/default.nix
- home/packages/windowmanager/hyprland/browser/qutebrowser.nix
- themes/gtk/default.nix
- **patch(themes/gtk): specify gtk-versions pkgs**
- **feat(home/pkgs/browser): add chromium**
- **patch(home/pkgs/chromium): update --enable-features**
> feat(home/pkgs/browser): add chromium

- flake.lock
- flake.nix
- **chore(flake): update inputs.{chaotic,chaotic-kernel,nixpkgs}**
- **chore(flake): update all other inputs**
> chore(flake): update all upstream inputs

- profiles/server/mars/configuration.nix
- system/users/basic.nix
- system/users/default.nix
- system/users/fish.nix
- system/users/server.nix
- **refactor(system): rework users module**
- **patch(profiles/mars): remove unnecessary modules**
> refactor(system): rework users module

- flake.lock
Reverts miooochi/nixos-config#204
> Revert "chore(flake) update flake.lock"

- home/apps/mpv/default.nix
- home/apps/mpv/mpv.conf
- **patch(home/apps/mpv): update mpv config**
- **feat(home/apps/mpv): add uosc support**
> patch(home/apps/mpv): update mpv configs

- flake.lock
- flake.nix
- home/packages/wayland/default.nix
- profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
- system/services/windowmanager/hyprland.nix
> patch: switch wm to hyprland-v0.41.0

- profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
- **patch(profile/x1-carbon): use xe module**
- **patch(profile/x1-carbon): enable mesa-git**
> patch(profile/x1-carbon): enable mesa-git

- home/services/xdg/default.nix
- home/themes/cursor.nix
- **patch(home/themes/cursor): update default cursor size from 24 to 52**
- **patch(home/svc/xdg): set default browser to firefox-nightly**
> patch(home/themes/cursor): update default cursor size from 24 to 52

- home/packages/windowmanager/browser/firefox.nix
- system/services/xdg-portal.nix
Ref: https://github.com/hyprwm/Hyprland/blob/main/flake.nix#L91
> feat(system/svc/xdg-portal): add hyprland portal

- flake.lock
- chaotic
- pre-commit-hooks
- sops-nix
- nixpkgs-wayland
> chore(flake): update locks

- flake.lock
Reverts piyoki/nixos-config#275
> Revert "chore(flake) update flake.lock for the selected upstream inputs"

- flake.lock
- flake.nix
- profiles/server/reverse-proxy/modules/networking.nix
- profiles/server/reverse-proxy/modules/services.nix
- profiles/workstation/9900x-desktop/configuration.nix
- profiles/workstation/9900x-desktop/modules/hosts.nix
- **chore(flake): update inputs.home-estate**
- **patch(profiles/reverse-proxy): update caddy service config**
- **feat(profiles/9900x-desktop): enable hosts module**
> patch(profile/reverse-proxy): update caddy service config

- flake.lock
- profiles.nix
- profiles/server/dns-resolver/configuration.nix
- profiles/server/dns-resolver/hardware-configuration.nix
- profiles/server/dns-resolver/modules/networking.nix
- profiles/server/dns-resolver/modules/services.nix
- profiles/workstation/9900x-desktop/configuration.nix
- **chore(flake): update inputs.{nur,home-estate}**
- **feat(profiles/server): add dns-resolver host profile**
> feat(profiles/server): add dns-resolver host profile

- flake.lock
- profiles/workstation/9900x-desktop/configuration.nix
- profiles/workstation/thinkpad-x1-carbon/configuration.nix
- **feat(profiles/workstation): enable resolved**
- **chore(flake): update inputs.home-estate**
> feat(profiles/workstation): enable resolved

- README.md
- flake.lock
- flake.nix
- home/packages/wayland/default.nix
- system/services/windowmanager/hyprland.nix
- **docs(readme): add pyprland to upstream inputs list**
- **chore(flake): add inputs.pyprland**
- **patch(system/svc/hyprland): add hyprland pkg**
- **feat(home/pkgs): add wev (wayland event viewer)**
> feat(flake): integrate pyprland

- profiles/workstation/9900x-desktop/configuration.nix
- profiles/workstation/9900x-desktop/hardware-configuration.nix
- profiles/workstation/thinkpad-x1-carbon/configuration.nix
- profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
- system/services/btrfs.nix
- system/services/default.nix
(cherry picked from commit 0aed9a916b085f6d3e94de3770fb57b09687ba41)
> refactor(system/svc): rework btrfs autoscrub integration

- home/services/default.nix
- home/services/dunst/default.nix
- system/services/windowmanager/hyprland/default.nix
- system/services/windowmanager/hyprland/hypridle.nix
- **refactor(home/services): rework service import; disable swayidle**
- **feat(system/services/hyprland): add hypridle module**
> feat(system/services/hyprland): add hypridle module

- flake.lock
- system/services/windowmanager/hyprland/default.nix
- system/services/windowmanager/hyprland/hypridle.nix
- system/services/windowmanager/hyprland/hyprlock.nix
- **feat(system/svc/hyprland): add hyprlock module**
> feat(system/svc/hyprland): add hyprlock module

- system/environment/default.nix
- system/environment/development.nix
- system/environment/system.nix
- system/packages/core.nix
- **feat(system/pkg): add pkg-config**
- **refactor(system/environment): set openssl-path default dir path**
- **refactor(system/enviromment): rework environment module**
> refactor(system/environment): set openssl-path default dir path

- system/environment/development.nix
- system/environment/system.nix
- system/hardware/audio.nix
- **patch(system/audio): disable pipewire.jack**
- **feat(system/environment): add ld_library_path**
- **patch(system/environment): update default app vars**
> fix(system/environment): fix broken ld_library_path var

- flake.lock
- flake.nix
- profiles/workstation/9900x-desktop/hardware-configuration.nix
- profiles/workstation/thinkpad-x1-carbon/configuration.nix
- system/environment/intel-specific.nix
- system/environment/system.nix
- **patch(system/environment): fix cursor lagging issue since kernel 6.11.0+**
- **chore(flake): update inputs.chaotic-kernel (6.11.5)**
- **patch(profiles/9900x-desktop): enable amdgpu.freesync_video**
- **patch(profiles/x1-carbon): include intel-specific environment**
- **chore(flake): update inputs.chaotic-kernel, roll back to (6.10.10)**
> patch(system): apply a few system patches

- flake.lock
- home/packages/windowmanager/productivity/default.nix
- system/services/scx.nix
- **patch(home/pkgs): switch to stable alacritty from nixpkgs**
- **chore(flake): update inputs.chaotic**
- **patch(system/svc): update scx pkgs to scx_git.full**
> patch(inputs.chaotic): apply a few system,home patches

- docs/bootstrap-system.md
- flake.lock
- home/packages/windowmanager/browser/firefox.nix
- home/packages/windowmanager/media/default.nix
- home/packages/windowmanager/terminal/default.nix
- home/services/password-manager/yubikey.nix
- shared/nixos.nix
- system/packages/core.nix
- system/packages/stable.nix
- **patch(shared/nixos): update gc cron from 3d to 14d**
- **patch(home/pkgs): remove cava**
- **patch(home/pkg/firefox): switch to firefox-nightly**
- **refactor(system/pkg): migrate tspin**
- **docs(bootstrap-system): update default params**
- **chore(flake): update inputs.{nixpkgs,home-manager}**
- **refactor(home/svc/password-manager): migrate yubikey-desktop**
> patch(system): apply a few system patches; update pkgs.yubikey-desktop 

- docs/bootstrap-system.md
- flake.lock
- home/packages/windowmanager/browser/firefox.nix
- home/packages/windowmanager/media/default.nix
- home/packages/windowmanager/terminal/default.nix
- home/services/password-manager/yubikey.nix
- shared/nixos.nix
- system/packages/core.nix
- system/packages/stable.nix
Reverts piyoki/nixos-config#383
> Revert "patch(system): apply a few system patches; update pkgs.yubikey-desktop "

- flake.lock
- flake.nix
- home/packages/development/lsp/default.nix
- home/packages/stable/default.nix
- home/packages/windowmanager/document/default.nix
- home/packages/windowmanager/media/default.nix
- home/packages/windowmanager/terminal/default.nix
- home/services/password-manager/yubikey.nix
- system/packages/core.nix
- system/packages/stable.nix
- **chore(flake): update inputs.{nixpkgs,nixpkgs-stable}; pin stable to 24.11-beta**
- **patch(pkgs/home): remove libreoffice-fresh**
- **patch(pkgs/home/lsp): buf-language-server -> buf**
- **refactor(home/pkg): tidy up packages**
- **chore(flake): update inputs.nixpkgs-stable; pin to 24.05**
- **chore(flake): update inputs.hyprland (0.45.2)**
> patch(system): apply a few system patches; update nixpkgs

- flake.lock
- flake.nix
- profiles/workstation/9900x-desktop/hardware-configuration.nix
- profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
- **chore(flake): update inputs.chaotic-kernel (6.12.8)**
- **patch(profiles/workstation): update kernel ref**
- **chore(flake): update inputs.chaotic-kernel (5edcf7f)**
> chore(flake): update inputs.chaotic-kernel (6.12.8)

- flake.lock
- flake.nix
- home/libs/qt/default.nix
- home/packages/windowmanager/document/default.nix
- home/packages/windowmanager/system/default.nix
- shared/vars/default.nix
- system/hardware/audio.nix
- system/security/polkit.nix
- themes/fonts/common-fonts.nix
- themes/qt/default.nix
- **patch: resolved incompatible options and conflicts**
- **chore(flake): update inputs.nixpkgs-wayland**
- **patch(flake.nix): resolve pkgs inherit issue**
- **patch(themes/qt): update default theme configs**
- **chore(flake): update inputs.hyprland (v0.48.1)**
- **chore(flake): update inputs.home-estate**
> chore(flake): update inputs.nixpkgs; resolve incompatible issues and conflicts

- flake.nix
- profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
- shared/config/default.nix
- shared/config/intel-gpu.nix
- **refactor(flake): extract config to shared module**
- **refactor(profile/x1-carbon): migrate intel-gpu overrides to shared/config/intel-gpu module**
- **patch(flake): ensure pkgs-stable uses legacy config option**
> refactor(flake): rework nixpkgs config definition

- .github/workflows/cron-sync-upstream-inputs.yml
- README.md
- flake.lock
- flake.nix
- system/services/windowmanager/hyprland/hyprlock.nix
- system/services/windowmanager/hyprland/hyprpaper.nix
- **feat(system/svc/windowmanager/hyprland): fetch hyprlock,hyprpaper pkgs from upstream inputs**
- **ci(workflows/cron-sync-upstream-inputs): add hyprlock,hyprpaper**
> feat(system/svc/windowmanager/hyprland): fetch hyprlock,hyprpaper pkgs from upstream inputs
